### ISSUE TITLE
Only render the tooltip DOM when it's active

### ISSUE THREAD

**Issue by MartijnHols** [bsidelinger912/react-tooltip-lite#31]
Making the lightweight tooltips even more lightweight 😅 

Currently the tooltip is rendered in its portal regardless of it being active or not. Adding elements to the DOM comes with a cost. While it won't be a major part of any page's performance, considering web performance is usually death by a thousand cuts, this adds as many cuts as tooltips you have on a page - which may be many.

I'm making this issue to see if there's any interest in this. I already wrote [the code for this](https://github.com/bsidelinger912/react-tooltip-lite/compare/master...WoWAnalyzer:322867d6273f4a8cb4afcba496be66844ad97eb6) in my fork, and if this is something you would want I can rebase it.

It might look like the changes in the link above are a lot, but actually the majority of it is moving the actual tooltip code to its own component. The only real changes are the conditional rendering of the Tooltip component and the `forceUpdate` in the Tooltip component.

I'm well aware `forceUpdate` is "bad practice", but this is necessary due to `positions` relying on the rendered tooltip. I reckon `forceUpdate` is available for exactly this situation.

**Comment by bsidelinger912** [comment]
Hey @MartijnHols, this is something I've thought about before.  I was weighing the cost of adding and removing the element from the DOM every time you show or hide the tip, vs the initial render being more expensive.  I can see how the cost of initial render could add up with a lot of tooltips on a page for sure.  I wonder about the specific cost of adding and removing an element vs changing inline style rules, I know both techniques will force a layout calculation so it could be about the same, in which case your idea is probably the lesser evil. However, I just got the idea of using a css transform/translate instead of changing the left property.  Transform won't require a layout calculation, and would be the most performant after initial render.  However, we'd still need to weight the cost of initial render vs the subsequent DOM changes.  One could argue that when the tip is activated not much else is going on, so deferring the perf hit, even if it was a higher cost, would still be the best strategy because initial render is the thing that is the most expensive and needs the most optimization.  Maybe an even better strategy is to not render into the DOM until the first activation, then hide/show it with transform/translate from then on.  That kinda seems like the best of both worlds to me and I don't think it'd be too terribly difficult to implement.  How does that strike you?
