### ISSUE TITLE
onClick doesn't work as expected

### ISSUE THREAD

**Issue by samjross** [bsidelinger912/react-tooltip-lite#36]
I have an element which looks like this:

```
                                   <Tooltip
                                        content={discount.discount_no || discount.discount_name}
                                        direction="right"
                                        tagName="button"
                                        className="target"
                                        useDefaultStyles={true}
                                        key={discount.discount_no || discount.discount_name}
                                        onClick={() => this.check(discount)}
                                    >
                                        {discount.discount_name}
                                    </Tooltip>
```

When I click the 'button' that the tooltip element outputs, it does not do `this.check()`. When I write it like the below way, it works:

```
                                    <Tooltip
                                        content={discount.discount_no || discount.discount_name}
                                        direction="right"
                                        tagName="button"
                                        className="target"
                                        useDefaultStyles={true}
                                        key={discount.discount_no || discount.discount_name}
                                    >
                                        <span onClick={() => this.check(discount)}>{discount.discount_name}</span>
                                    </Tooltip>
```

**Comment by bsidelinger912** [comment]
Hey @samjross onClick is not a supported prop on the Tooltip, all the supported props are documented in the README

**Comment by samjross** [comment]
Hiya, thank you for the response. In that case make this a feature request

Having thought about it a bit more though... maybe it's completely unnecessary, as you could always just use the Tooltip to output a span, and wrap it in some element you want to click... I'm not so sure anymore.

**Comment by bsidelinger912** [comment]
Yeah, I'm trying to get away from the component being a proxy for all jsx functionality.  Ideally it wouldn't even insert a DOM node at all, what would be required for that is for fragments to handling events that bubbled up from real DOM nodes.  I'm actually working on adding that functionality in a fork of React currently, as the maintainers do seem open to it: https://github.com/facebook/react/issues/12051.  So as you can see, adding event handlers as well as other native jsx props will go against my goals in this regard.  I added the ability to specify the element type and add a className to it just so that the addition of the real DOM element (who's only job is to capture bubbling events) is controllable enough so that you can stop it from ruining your layouts.

**Comment by bsidelinger912** [comment]
Closing as I don't intend to be have the tooltip be a passthrough for events and other jsx props as described above.
