### ISSUE TITLE
Tooltip disappears only after you hover mouse over it and then leave it

### ISSUE THREAD

**Issue by FIIFE** [bsidelinger912/react-tooltip-lite#46]
I have a list of buttons of the following structure:
`<Tooltip content='Cannot delete because' hoverDelay={50}>
        <button disabled className='someButton'><FontAwesomeIcon icon='trash-alt' /></button>
</Tooltip>`

When i hover over the buttons the tooltip appears but it doesn't disappear until i hover over the tooltip itself and then leave its area with a cursor. There can be multiple tooltips persisting indefinitely

**Comment by bsidelinger912** [comment]
Hi @FIIFE, this is caused by https://github.com/facebook/react/issues/4251, which seems to be a browser issue at it's core.  I'll try and find a workaround.

**Comment by bsidelinger912** [comment]
Hi @FIIFE, I tinkered with this a bit and it was pretty easy to fix, with the same workaround described in the react issue I linked which was to use `pointer-events: none` In your case this had to be applied to disabled buttons like so:
```
button:disabled {
   pointer-events: none;
}
```
Doing this lets the event bubble up to the wrapper element instead of having the disabled button swallow it as is the standard behavior in several browsers.  Since all the automatic styling for react-tooltip-lite is inline, then we can't do this inside the package at the moment, but it's easy to work around it on your own.
