### ISSUE TITLE
Fade affect

### ISSUE THREAD

**Issue by YonatanHanan** [bsidelinger912/react-tooltip-lite#65]
Is there a way I could implement a fade transition?

**Comment by bsidelinger912** [comment]
Hey @YonatanHanan I can't think of an easy way now because we actually hide the tooltip off the screen.  However I may be able to add a class that shows up when it's visible and goes away when it's not and you could then apply a CSS transition on that class.  I'll try that out when I'm working through other issues this week (finally getting back to a bunch of this stuff)

**Comment by bsidelinger912** [comment]
@YonatanHanan I think this can be done now by changing the "tipContentClassName" prop when the new "onToggle" prop fires.  You can conditionally add a class with a css transition.

**Comment by bsidelinger912** [comment]
Closing for now since this seems to be resolved.
