### ISSUE TITLE
Set max-width on Tooltip

### ISSUE THREAD

**Issue by AB1519** [bsidelinger912/react-tooltip-lite#79]
Hi I am trying to overwrite the max-width on the tooltip. 
I have tried implementing the styles props but it is not working. can anyone please help me

<Tooltip 
styles={{maxWidth: 100}}
/>

styles property is not working.

**Comment by bsidelinger912** [comment]
Hi @AB1519 the styles prop is to enable overrides for the wrapper element we put around your "target", since we insert an element in the dom to grab events from we allow some props such as styles to be passed through.  For what you want, you can just style the tips content yourself, since you can pass JSX to the content prop.  Just wrap your content in a <div> or whatever and add a class or a styles prop to that and the tooltip will only stretch to accommodate with that your content requires.   For example: 
```
           <Tooltip
              content={(
                <div style={{ maxWidth: 100 }}>
                  <h4 className="tip-heading">An unordered list to demo some html content</h4>
                  <ul className="tip-list">
                    <li>One</li>
                    <li>Two</li>
                    <li>Three</li>
                    <li>Four</li>
                    <li>Five</li>
                  </ul>
                </div>
              )}
            >
             This is the "target"
            </Tooltip>
```

**Comment by bsidelinger912** [comment]
Closing as I believe the solution is provided in my answer.
